package net.thinksquared.lilldep.database;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.sql.*;
import java.util.Iterator;
public class BaseCollection  { 
	public static final String MEMO  = "COLLECTION.MEMO"; 
	public static final String COLLECTION_ID  = "COLLECTION.COLLECTION_ID"; 
	protected String memo; 
	protected int collectionId; 
	protected String name; 
	protected boolean saved  = false; 
	public static final String NAME  = "COLLECTION.NAME"; 

	public void save()
	throws Exception{ 
		if(saved){
			BaseCollectionPeer.doUpdate(this);
		}else{
			BaseCollectionPeer.doInsert(this);
		}
	} 

	public String getName(){ 
		return name;
	} 

	public void setMemo(String args0){ 
		memo =args0;
	} 

	public String getMemo(){ 
		return memo;
	} 

	/**
	  * collectionId is autogenerated 
	*/
	public int getCollectionId(){ 
		return collectionId;
	} 

	public void setName(String args0){ 
		name =args0;
	} 
}