package net.thinksquared.lilldep.database;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.sql.*;

public class BaseCollectionMapPeer  { 

	public static void doInsert(BaseCollectionMap args0)
	throws Exception{
        Connection connection = Database.getConnection(); 
        doSave(args0,false,connection);
        Database.release(connection);
	} 

	public static void doInsert(BaseCollectionMap args0,Connection connection)
	throws Exception{ 
        doSave(args0,false,connection);
	} 

	public static void doUpdate(BaseCollectionMap args0)
	throws Exception{ 	
        Connection connection = Database.getConnection(); 
        doSave(args0,true,connection);
        Database.release(connection);
    }

	public static void doUpdate(BaseCollectionMap args0,Connection connection)
	throws Exception{ 	
        doSave(args0,true,connection);
    }

	private static void doSave(BaseCollectionMap args0, boolean isUpdate, Connection connection)
	throws Exception{ 

        Statement statement = connection.createStatement();        
        String query = "";
        if(isUpdate){
            query = "UPDATE collection_map SET " + " collection_id = " + Criteria.escape(args0.getCollectionId()) + " , " + " contact_id = " + Criteria.escape(args0.getContactId()) + " WHERE ";
            statement.executeUpdate(query);
        }else{
            query = "INSERT INTO collection_map ( collection_id , contact_id ) VALUES ( " + Criteria.escape(args0.getCollectionId()) + " , " + Criteria.escape(args0.getContactId()) + " )";         
            statement.execute(query,Statement.RETURN_GENERATED_KEYS);
            ResultSet rs = statement.getGeneratedKeys();
            if(rs.next()){
                ;
            }
        }   
        statement.close();  
        args0.saved = true;      
	}
 
	public static void doDelete(Criteria args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(Criteria args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate(args0.deleteSQL("COLLECTION_MAP"));
        statement.close();
    } 

	public static void doDelete(BaseCollectionMap args0)
	throws Exception{ 
        Connection connection = Database.getConnection();
        doDelete(args0,connection);
        Database.release(connection);
    } 

	public static void doDelete(BaseCollectionMap args0, Connection connection)
	throws Exception{ 
        Statement statement = connection.createStatement();
        statement.executeUpdate("DELETE FROM collection_map WHERE ");
        statement.close();
        args0.saved = false; 	
    } 

	public static Scroller doSelect(Criteria args0)
	throws Exception{ 
		return doSelect(args0.selectSQL("COLLECTION_MAP.COLLECTION_ID,COLLECTION_MAP.CONTACT_ID","COLLECTION_MAP"));
	} 

	public static Scroller doSelect(String sql)
	throws Exception{         
        return new  CollectionMapScroller(sql,false);
	} 

	public static Scroller doSelect(Criteria args0, boolean recycle)
	throws Exception{ 
		return doSelect(args0.selectSQL("COLLECTION_MAP.COLLECTION_ID,COLLECTION_MAP.CONTACT_ID","COLLECTION_MAP"),recycle);
	} 

	public static Scroller doSelect(String sql, boolean recycle)
	throws Exception{         
        return new  CollectionMapScroller(sql,recycle);
	} 

	protected static CollectionMap getBean(ResultSet results, CollectionMap ret)
	throws Exception{ 

				ret.collectionId=results.getInt("COLLECTION_ID");
				ret.contactId=results.getInt("CONTACT_ID");
        
    
        ret.saved = true;        
                
        return ret;   
	} 


    private static class CollectionMapScroller implements Scroller{

        Statement statement;
        ResultSet results;   
        boolean recycle = false;  
        CollectionMap cache = null;    

        private CollectionMapScroller(String sql,boolean recycle) throws Exception{

            Connection connection = Database.getConnection();
            statement = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            results = statement.executeQuery(sql);
            Database.release(connection);
            this.recycle = recycle;
            
        }

        public Object next(){        
            try{     
                cache = (recycle && cache != null)?  BaseCollectionMapPeer.getBean(results, cache) : 
                                                     BaseCollectionMapPeer.getBean(results, new CollectionMap());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasNext(){
            try{
                if(results.next()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public Object previous(){        
            try{     
                cache = (recycle && cache != null)?  BaseCollectionMapPeer.getBean(results, cache) : 
                                                     BaseCollectionMapPeer.getBean(results, new CollectionMap());
                return cache;
            }catch(Exception ignore){
                return null;
            }
        }

        public boolean hasPrevious(){
            try{
                if(results.previous()){
                    return true;
                }else{
                    return false;   
                }
            }catch(Exception ignore){
                return false;
            }
        }

        public void absolute(int position){
            try{results.absolute(position);}catch(Exception ignore){}    
        }

        public void remove() throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }
        public int  size()   throws UnsupportedOperationException{ throw new UnsupportedOperationException(); }

        protected void finalize() throws Throwable{
            try{statement.close();}catch(Exception ignore){}
        }

    }


}
