package net.thinksquared.lilldep.database;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.sql.*;
import java.util.Iterator;
public class Collection extends BaseCollection { 

    /**
     * Gets a Scroller containing all Contacts for
     * this Collection.
     **/    
    public Scroller getContacts()
    throws Exception{

        Criteria crit = new Criteria();
        crit.addJoin(Contact.CONTACT_ID, CollectionMap.CONTACT_ID);
        crit.add(CollectionMap.COLLECTION_ID, getCollectionId());
        return ContactPeer.doSelect(crit);

    }

}