package net.thinksquared.lilldep.database;
/**
  * Autogenerated by Lisptorq 0.1.4 
*/
import java.sql.*;
import java.util.Iterator;
public class CollectionMap extends BaseCollectionMap { 

	public void save()
	throws Exception{ 
			BaseCollectionMapPeer.doInsert(this);
	} 

}