package net.thinksquared.lilldep.database;
/**
  * Autogenerated by Lisptorq 0.1.3
*/
import java.sql.*;
import java.util.Iterator;
import java.util.Map;
public class Contact extends BaseContact implements java.io.Serializable, Cloneable{

    public Contact(){}

    public Contact(Map m){

        setName(get("NAME",m));
        setDepartment(get("DEPARTMENT",m));
        setDesignation(get("DESIGNATION",m));
        setEmail(get("EMAIL",m));
        setTel(get("TEL",m));
        setFax(get("FAX",m));
        setCompany(get("COMPANY",m));
        setAddress(get("ADDRESS",m));
        setPostcode(get("POSTCODE",m));
        setCountry(get("COUNTRY",m));
        setWebsite(get("WEBSITE",m));
        setActivity(get("ACTIVITY",m));
        setClassification(get("CLASSIFICATION",m));
        setMemo(get("MEMO",m));

    }

    public String get(String key, Map m){
        Object o = m.get(key);
        return (o == null)? "" : (String)o;
    }


    public void clear(){
	   memo = activity = country = address = 
       fax = email = designation = name = 
       department = tel = company = postcode =
       website = classification = ""; 
    }

    public Contact klone(){
        try{
            return (Contact)clone();
        }catch(CloneNotSupportedException cnse){
            return null;
        }
    }
 
}