package net.thinksquared.lilldep.database;
/**
  * Autogenerated by Lisptorq 0.1.3 
*/
import java.sql.*;
import java.util.Iterator;
public class ContactPeer extends BaseContactPeer { 

    public static Scroller find(Contact query){

        final String WC = "%";
        
        Criteria crit = new Criteria();

        if(query.getName().length() > 0){
            crit.add(Contact.NAME, WC + query.getName() + WC, Criteria.LIKE);
        }

        if(query.getDesignation().length() > 0){
            crit.add(Contact.DESIGNATION, WC + query.getDesignation() + WC, Criteria.LIKE);
        }

        if(query.getDepartment().length() > 0){
            crit.add(Contact.DEPARTMENT, WC + query.getDepartment() + WC, Criteria.LIKE);
        }

        if(query.getCompany().length() > 0){
            crit.add(Contact.COMPANY, WC + query.getCompany() + WC, Criteria.LIKE);
        }

        if(query.getPostcode().length() > 0){
            crit.add(Contact.POSTCODE, WC + query.getPostcode() + WC, Criteria.LIKE);
        }

        if(query.getAddress().length() > 0){
            crit.add(Contact.ADDRESS, WC + query.getAddress() + WC, Criteria.LIKE);
        }

        if(query.getActivity().length() > 0){
            crit.add(Contact.ACTIVITY, WC + query.getActivity() + WC, Criteria.LIKE);
        }

        if(query.getMemo().length() > 0){
            crit.add(Contact.MEMO, WC + query.getMemo() + WC, Criteria.LIKE);
        }

        if(query.getClassification().length() > 0){
            crit.add(Contact.CLASSIFICATION, WC + query.getClassification() + WC, Criteria.LIKE);
        }

        if(query.getEmail().length() > 0){
            crit.add(Contact.EMAIL, WC + query.getEmail() + WC, Criteria.LIKE);
        }

        if(query.getWebsite().length() > 0){
            crit.add(Contact.WEBSITE, WC + query.getWebsite() + WC, Criteria.LIKE);
        }

        if(query.getTel().length() > 0){
            crit.add(Contact.TEL, WC + query.getTel() + WC, Criteria.LIKE);
        }

        if(query.getFax().length() > 0){
            crit.add(Contact.FAX, WC + query.getFax() + WC, Criteria.LIKE);
        }

        if(query.getCountry().length() > 0){
            crit.add(Contact.COUNTRY, WC + query.getCountry() + WC, Criteria.LIKE);
        }

        if(crit.isEmpty()) return null; //don't return the whole database

        try{

            return doSelect(crit);

        }catch(Exception ignore){

            return null;
        }

    }

}