package net.thinksquared.lilldep.database;
/**
  * Autogenerated by Lisptorq 0.1.4 
  * from database-setup.template
*/
import java.sql.*;
public final class DatabaseSetup{ 

    public static void main(String[] args) throws Exception{

        Database dbase = new Database(); //one-time initialization

        Connection conn = dbase.getCreationConnection();
        conn.setAutoCommit(false);
        Statement stmt = conn.createStatement();
    
		stmt.execute("CREATE TABLE contact ( contact_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 , INCREMENT BY 1 )  , name VARCHAR(1024)  , designation VARCHAR(1024)  , department VARCHAR(1024)  , email VARCHAR(255)  , tel VARCHAR(255)  , fax VARCHAR(255)  , company VARCHAR(1024)  , address VARCHAR(1024)  , postcode VARCHAR(16)  , country VARCHAR(255)  , website VARCHAR(255)  , activity VARCHAR(2048)  , classification VARCHAR(16)  , memo VARCHAR(2048)  , PRIMARY KEY ( contact_id ) )");
		stmt.execute("CREATE TABLE collection ( collection_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 , INCREMENT BY 1 )  , name VARCHAR(1024)  , memo VARCHAR(2048)  , PRIMARY KEY ( collection_id ) )");
		stmt.execute("CREATE TABLE collection_map ( collection_id INTEGER NOT NULL , FOREIGN KEY ( collection_id ) REFERENCES collection ( collection_id )  , contact_id INTEGER NOT NULL , FOREIGN KEY ( contact_id ) REFERENCES contact ( contact_id )  )");
    

        conn.commit();
        conn.close();
        Database.shutdown();    
    }

}
